name: Build and Release Executables

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev

    - name: Tidy Go Modules
      run: go mod tidy

    - name: Build Executable (Windows)
      if: matrix.os == 'windows-latest'
      run: go build -o luigi-ssh-manager.exe main.go

    - name: Build Installer (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Build Executable (macOS)
      if: matrix.os == 'macos-latest'
      run: go build -o luigi-ssh-manager-macos main.go

    - name: Build Executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: go build -o luigi-ssh-manager-linux main.go

    - name: Upload Artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: luigi-ssh-manager-windows
        path: dist/LuigiSSHManager-Setup.exe

    - name: Upload Artifact (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: luigi-ssh-manager-linux
        path: luigi-ssh-manager-linux

    - name: Upload Artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: luigi-ssh-manager-macos
        path: luigi-ssh-manager-macos

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/luigi-ssh-manager-windows/LuigiSSHManager-Setup.exe
          artifacts/luigi-ssh-manager-linux/luigi-ssh-manager-linux
          artifacts/luigi-ssh-manager-macos/luigi-ssh-manager-macos
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
